export const SET_THEME = "SET_THEME";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_PROJECT_BEGIN = "GET_PROJECT_BEGIN";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const GET_ALL_PROJECTS_BEGIN = "GET_ALL_PROJECTS_BEGIN";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const SET_EDIT_PROJECT = "SET_EDIT_PROJECT";

export const DELETE_PROJECT_BEGIN = "DELETE_PROJECT_BEGIN";

export const EDIT_PROJECT_BEGIN = "EDIT_PROJECT_BEGIN";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";

export const SUBMIT_FORM_DATA = "SUBMIT_FORM_DATA";

export const PUBLISH_PROJECT_BEGIN = "PUBLISH_PROJECT_BEGIN";
export const PUBLISH_PROJECT_SUCCESS = "PUBLISH_PROJECT_SUCCESS";

export const NEXT_SECTION = "NEXT_SECTION";

export const LOGOUT_USER = "LOGOUT_USER";
